### PR TITLE
Update/tabs vue component

### PR DESCRIPTION
**Pull request by TristanMNorton**
I think I have the baseline functionality ready to rock. Note: I want us to all be kosher with this before style polish, transitions etc.

I made all functionality to be compliant as defined here:
https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

@khamer , I was building this while in the pattern library and I think it was borking location hash stuff since it's rendered in an iframe. I think it should still work though?

### CODE REVIEW

**Comment by TristanMNorton** [comment]
Figured out you can open a component in it's own window in fractal. I can confirm that the hash is getting updated in the url and getting added to history, however, navigating back does not update the tab. So I'll need to fix that.

**Comment by marcelmoreau** [comment]
Great job...it's improving from where this once was.
- you don't need `role="button"` on the `<button>`
- I cannot really tab through anything. I load the preview page, I start to tab. I focus on first tab, then the content area, then Chrome puts the focus to my browser tabs. I want to "write never use `tabindex="-1"`" as this removes an element from natural tabbing order, but the [article I always reference ](https://developers.google.com/web/fundamentals/accessibility/focus/using-tabindex) says that the element can still focused if you call its focus() method. I think you may be doing that. I would expect to be able to tab to the second tab, activate it (which puts focus on content area), then shift+tab back up to the tabs in order to go to the third tab perhaps.

**Comment by TristanMNorton** [comment]
We might need to decide on what our authoritative source is on this. I'm simply adhering to what's described by w3 here:

https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html#kbd_label

You can see that their example works the exact same way as well. I actually think it makes perfect sense too since by making "tab" the means to progressing through tabs, you're _forcing_ the user to progress through all the tabs before moving through the rest of the page.

If you think about how we use a mouse and why tabs are a thing, it's to offer the _choice_ to view new content hidden behind tabs. Like we get to when scrolling through a page.

By making tabs navigable by arrow key, the user can use the arrow keys to view the other tabs, or simply continue through the page if the don't want to.

**Comment by marcelmoreau** [comment]
@TristanMNorton you are 100% right. I didn't think it this this way.

**Comment by TristanMNorton** [comment]
@khamer @marcelmoreau @mbfitz 

I think this is good to merge. 

Tabs activate on focus now. I did some digging on the why's of manual tab activation and automatic tab activation. The consensus is unless the content isn't immediately available, (like obscured by an additional page or ajax request), the activation should be manual. Otherwise, always automatic. 

@khamer I also update the setHash method to use replaceState. I couldn't find anything specific on what best practice was, but none of the aria examples were pushing anything to state. I think having set hash is useful, but probably annoying to have the user click back through a bunch of tabs.

**Comment by khamer** [comment]
Merged - though I think you wanted to do some minor visual updates too so it wasn't just free floating tabs.

**Pull request merged**
