### PR TITLE
Updated accordian component to be accessible

### PR DESCRIPTION
**Pull request by TristanMNorton**
I think i've covered most of what will make this component accessible/compliant. Though it would be good to maybe have Robert or James take a look at it as well to get their thoughts. 

Note, I pretty much tried to do everything as defined in aria's guidelines for accordions.
https://www.w3.org/TR/wai-aria-practices-1.1/#accordion

### CODE REVIEW

**Comment by marcelmoreau** [comment]
this is sick...thanks

- we should not assume a headline level here `h3`– then we could ditch the `aria-level`
- we might consider ditching the `tabindex` attribute and just wrap our accordion headline in a native element that receives keyboard focus such as `button`. then we could also ditch `role="button`
- IIRC, I don't think we want to use `role="region"`…
- I don't have a great suggestion at the ready, but it might be nice if the `#content$` attribute maybe had `accordion` in its identifier? To more closely match its block?

**Comment by khamer** [comment]
I'm fine merging it as is, but here's my comments. I'll confirm whether you want me to merge now or wait.

* I'm also confused by why we need aria-level - shouldn't that be handled by the content within the heading slot?
* @marcelmoreau Is there an advantage to `<button>` over tab index? tabindex seems cleaner to me.
* @marcelmoreau I'm also not sure if I following what you mean about the content attribute; as it's written, the classes will be `.accordion__heading` and `.accordion__content`, as it uses both `block` and `headingElement`/`contentElement`.

* I might use `id` as the property instead of `identifier` - that seems more clear to me.
* I'd love to have auto-generated ids as a fallback instead of having to make them required; it'd make the component nicer to use. (Also, why would ARIA force us to use IDs for badly supported and implemented accessibility features?)

**Comment by TristanMNorton** [comment]
@khamer 

- Re: aria-level - Probably not, I'll remove it.
- Re: Identifier - I agree, I'll change it to "id"
- Re: Auto generated fallback for id. You thinking something like: https://www.npmjs.com/package/uuid? Also not sure what you mean by supported, but according to aria's doc on it: "The accordion header button element has aria-controls set to the ID of the element containing the accordion panel content." https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

@marcelmoreau I think you're right on role="region". The docs confused me a bit.

**Comment by khamer** [comment]
I don't think you need to use the UUID library - even just a simple id that increments

* https://jsfiddle.net/khamer/b6cj4hLn/
* or maybe even using Math.random() as suggested on [this Vue issue](https://github.com/vuejs/vue/issues/5886) - https://jsfiddle.net/khamer/qt1rb0o3/

Out of the two, I'm more partial to the second approach, but I don't feel strongly. We _could_ prefix the IDs if you felt that was important too (something like `${block}-${random stuff}` but I don't think that's really important, because if someone needed to use the ID they should be setting it.

**Comment by marcelmoreau** [comment]
@khamer @TristanMNorton 

- regarding naming, I was speaking of the `#content1`, `#content2`, etc elements that hold the accordion content. It might be nice to use the component's name in them e.g. `#accordion__content01`, etc. Also, hopefully multiple accordions on one page would have no issue with elements with same ID being used?
-using `tabindex="0"` is ok in this instance. I'd prefer button but it's fine. I am weary of introducing `tabindex`on our projects since a recently launched Imarc project went live with tabindex values greater than 0. This is an anti-pattern.
  - https://developers.google.com/web/fundamentals/accessibility/focus/using-tabindex
  - https://adrianroselli.com/2014/11/dont-use-tabindex-greater-than-0.html

**Comment by TristanMNorton** [comment]
Yeah definitely like the suggested math random. I don't want to use increment if there's more than one twig loop or something making duplicate values.

@marcelmoreau I think we're safe with tabindex="0" to simply add it to natural keyboard order. It think it's actually trying to control specific tab order with integers greater than 0 they're flagging as brittle.

**Comment by TristanMNorton** [comment]
I'll make the changes this afternoon then start on getting tabs converted to vue.

**Comment by marcelmoreau** [comment]
`tabindex="0"` is totally fine

**Comment by TristanMNorton** [comment]
@khamer @marcelmoreau Want to take one more look with the changes I made? Let me know if this is good to merge.

**Comment by marcelmoreau** [comment]
I disagree with assuming a heading level but if not one else feels anything about it, I am good

**Comment by marcelmoreau** [comment]
Also, FWIW, regarding headings and focus via tabindex

- Foundation doesn't use a heading or non-focusable element (`<a>`)
- Bootstrap doesn't use a heading or non-focusable element ('<button>`)
- Tailwind UI doesn't use a heading or non-focusable element (`<button>`)
- Codyhouse doesn't use a heading or non-focusable element (`<button>`)

**Comment by TristanMNorton** [comment]
Really doesn't matter to me what element we use as long as it's compliant. Everything I've read indicates that `role="button"` works well enough. However I'll opt for the zeitgeist and use what others are using. One more update incoming using <button>

**Comment by TristanMNorton** [comment]
Yeah @marcelmoreau , I consider MDN to be the horses mouth in this case:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#Best_practices

my b

**Comment by khamer** [comment]
Merged. My last comment would have been to use a default for the prop instead of a separate computed property:
```
props: {
  ...
  id: {
    type: String,
    default: () => Math.random()
  }
```

The only other thing I was doing was `Math.random().toString(36).substr(2)` which gives you a string like 'aafasom8vg7' instead of '0.25872487023100343' but it doesn't matter.

**Pull request merged**
